version: '3.4'

networks:
  comment-book-network:
    driver: bridge

services:

  apicommentbook:
    image: ${DOCKER_REGISTRY-}apicommentbook
    depends_on:
        - "postgres"
    build:
      context: .
      dockerfile: APICommentBook/Dockerfile
    ports:
        - "8000:30858"
    networks:
        - "comment-book-network"

  webappcommentbook:
    image: ${DOCKER_REGISTRY-}webappcommentbook
    depends_on:
        - "apicommentbook"
    build:
      context: .
      dockerfile: WebAppCommentBook/Dockerfile
    ports:
        - "8010:80"
    networks:
        - "comment-book-network"


  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=mydbname2
    volumes:
      - ./volumes1/data/db:/var/lib/postgresql/data
      - ./dbscripts:/docker-entrypoint-initdb.d
    ports:
       - 5432:5432
    restart: always
    networks:
        - "comment-book-network"
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "detulie@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "1Q2w3e4r5t"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - "comment-book-network"

